<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!--<ItemGroup>
    <Compile Remove="App_Data\documentation\NewFolder1\**" />
    <Compile Remove="App_Data\documentation\serviceSheets\**" />
    <Content Remove="App_Data\documentation\NewFolder1\**" />
    <Content Remove="App_Data\documentation\serviceSheets\**" />
    <EmbeddedResource Remove="App_Data\documentation\NewFolder1\**" />
    <EmbeddedResource Remove="App_Data\documentation\serviceSheets\**" />
    <None Remove="App_Data\documentation\NewFolder1\**" />
    <None Remove="App_Data\documentation\serviceSheets\**" />
  </ItemGroup>-->

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="NPOI" Version="2.7.3" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="wwwroot\img\images\" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
